version: '3.1'

services:
  frontend:
    entrypoint: ["npm", "start"]
    environment:
      NODE_ENV: development
    image: node:16.15-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/opt/frontend
    working_dir: /opt/frontend

  backend:
    entrypoint: ["npm", "start"]
    environment:
      NODE_ENV: development
    image: node:16.15-alpine
    ports:
      - "8080:8080"
    depends_on:
      - database
    volumes:
      - ./backend:/opt/backend
    working_dir: /opt/backend
  
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: hipages_pass
      MYSQL_DATABASE: hipagesDB
    ports:
      - "3366:3306"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d